# Generated by Django 5.0.7 on 2024-07-19 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_review_service', '0002_alter_review_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='users',
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('caption',)},
        ),
        migrations.RemoveField(
            model_name='review',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='review',
            name='likes',
        ),
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hotel_review_service.hotel'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserReviewReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('L', 'Liked'), ('D', 'Disliked')], max_length=1, null=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_review_service.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='reviews_reacted',
            field=models.ManyToManyField(related_name='reacted_by', through='hotel_review_service.UserReviewReaction', to='hotel_review_service.review'),
        ),
        migrations.DeleteModel(
            name='ReviewUser',
        ),
    ]
