# Generated by Django 5.0.7 on 2024-07-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_review_service', '0003_remove_review_users_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RenameField(
            model_name='placement',
            old_name='address',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='hotelclass',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
